import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ThemeProvider from "./components/theme-provider";
import ThemeStatus from "./components/theme-status";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body>
          <header>
            <p>=== Root Layout Header ===</p>
            <nav>
              <Link href="/">Home</Link> | <Link href="/counter">Counter</Link><br/><br/>
              Slug Page Menu: &nbsp;
              <Link href="/nextjs">nextjs</Link>&nbsp; | &nbsp;
              <Link href="/routing">routing</Link>&nbsp; | &nbsp;
              <Link href="/ssr-ssg">ssr-ssg</Link>&nbsp; | &nbsp;
              <Link href="/dynamic-routes">dynamic-routes</Link>&nbsp; | &nbsp;
              # interleaving 예제: <Link href="/interleaved">interleaving 예제</Link>
            </nav>
            <ThemeStatus />
          </header>
          <main>
            {children}
          </main>
          <footer>=== Root Layout Footer ===</footer>
        </body>
      </html>
    </ThemeProvider>
  );
}
